test_that("submission package plans are deterministic", {
  project <- new_popgenvcf_project("submission-plan")
  manuscript <- new_manuscript(project, title = "Submission plan")
  directory <- tempfile()
  write_manuscript(manuscript, directory)
  first <- submission_package_plan(directory)
  second <- submission_package_plan(directory)
  expect_identical(first, second)
  expect_true(all(c("role", "source", "destination", "size_bytes", "sha256") %in% names(first)))
  expect_true(any(first$destination == "submission/manuscript.md"))
})

test_that("submission packages are written and verified", {
  project <- new_popgenvcf_project("submission-write")
  manuscript <- new_manuscript(project, title = "Submission write")
  directory <- tempfile()
  write_manuscript(manuscript, directory)
  archive <- tempfile(fileext = ".tar.gz")
  record <- write_submission_package(directory, archive)
  expect_s3_class(record, "PopgenVCFSubmissionPackage")
  expect_true(file.exists(archive))
  expect_true(verify_submission_package(archive))
  expect_error(write_submission_package(directory, archive), "already exists")
})

test_that("submission package verification detects corruption", {
  project <- new_popgenvcf_project("submission-corrupt")
  manuscript <- new_manuscript(project, title = "Submission corruption")
  directory <- tempfile()
  write_manuscript(manuscript, directory)
  archive <- tempfile(fileext = ".tar.gz")
  write_submission_package(directory, archive)
  extracted <- tempfile()
  dir.create(extracted)
  utils::untar(archive, exdir = extracted)
  writeLines("modified", file.path(extracted, "submission", "manuscript.md"))
  old <- setwd(extracted); on.exit(setwd(old), add = TRUE)
  utils::tar(archive, files = "submission", compression = "gzip", tar = "internal")
  expect_error(verify_submission_package(archive), "checksum mismatch")
})
