#!/usr/bin/env python3
"""Reconcile roxygen topics with retained grouped Rd manuals.

The repository contains curated grouped manuals that predate full roxygen
coverage. Roxygen may generate one-function topics for the same aliases. This
script removes a generated topic only when every alias it contains is already
covered by a retained non-generated manual. Mixed topics are rejected so no
unique documentation can be discarded accidentally.
"""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from pathlib import Path

GENERATED_MARKER = "% Generated by roxygen2: do not edit by hand"
ALIAS_PATTERN = re.compile(r"^\\alias\{(.*)\}$", re.MULTILINE)


def is_generated(path: Path) -> bool:
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()[:3]
    return GENERATED_MARKER in lines


def aliases(path: Path) -> tuple[str, ...]:
    text = path.read_text(encoding="utf-8", errors="replace")
    return tuple(ALIAS_PATTERN.findall(text))


def duplicate_aliases(paths: list[Path]) -> dict[str, list[Path]]:
    owners: dict[str, list[Path]] = defaultdict(list)
    for path in paths:
        for alias in aliases(path):
            owners[alias].append(path)
    return {alias: files for alias, files in owners.items() if len(files) > 1}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".", help="Repository root")
    parser.add_argument("--write", action="store_true", help="Delete fully covered generated topics")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    man_dir = root / "man"
    if not man_dir.is_dir():
        raise RuntimeError(f"missing manual directory: {man_dir}")

    paths = sorted(man_dir.glob("*.Rd"))
    generated = [path for path in paths if is_generated(path)]
    retained = [path for path in paths if not is_generated(path)]
    retained_aliases = {alias for path in retained for alias in aliases(path)}

    removable: list[Path] = []
    mixed: list[tuple[Path, tuple[str, ...], tuple[str, ...]]] = []
    for path in generated:
        topic_aliases = aliases(path)
        if not topic_aliases:
            continue
        covered = tuple(alias for alias in topic_aliases if alias in retained_aliases)
        unique = tuple(alias for alias in topic_aliases if alias not in retained_aliases)
        if covered and unique:
            mixed.append((path, covered, unique))
        elif covered:
            removable.append(path)

    if mixed:
        print("Generated Rd topics mix retained and unique aliases:")
        for path, covered, unique in mixed:
            print(f"- {path.relative_to(root)}")
            print(f"  retained: {', '.join(covered)}")
            print(f"  unique: {', '.join(unique)}")
        return 2

    if removable and not args.write:
        print(f"{len(removable)} generated Rd topic(s) duplicate retained manuals:")
        for path in removable:
            print(f"- {path.relative_to(root)}")
        return 1

    if args.write:
        for path in removable:
            path.unlink()
        print(f"Removed {len(removable)} generated topic(s) fully covered by retained manuals.")

    remaining = sorted(man_dir.glob("*.Rd"))
    duplicates = duplicate_aliases(remaining)
    if duplicates:
        print("Duplicate Rd aliases remain after reconciliation:")
        for alias in sorted(duplicates):
            owners = ", ".join(str(path.relative_to(root)) for path in duplicates[alias])
            print(f"- {alias}: {owners}")
        return 2

    print(
        "Rd aliases are unique across "
        f"{len(remaining)} topics ({sum(is_generated(path) for path in remaining)} generated, "
        f"{sum(not is_generated(path) for path in remaining)} retained)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
