# Dynamic namespace synchronization for the Phase 0.9 publication-report and
# canonical real-data APIs. These exports are registered at namespace load so
# the implementation remains usable before the next generated NAMESPACE pass.
.onLoad <- function(libname, pkgname) {
  ns <- asNamespace(pkgname)
  namespaceExport(ns, c(
    "new_publication_report_spec",
    "validate_publication_report_spec",
    "new_publication_report_plan",
    "validate_publication_report_plan",
    "new_publication_report_output_manifest",
    "validate_publication_report_output_manifest",
    "publication_report_plan_report",
    "new_publication_report_renderer",
    "validate_publication_report_renderer",
    "quarto_publication_report_renderer",
    "execute_publication_report_plan",
    "validate_publication_report_execution",
    "publication_report_execution_report",
    "new_publication_layout_profile",
    "validate_publication_layout_profile",
    "publication_layout_profile",
    "bind_publication_layout",
    "validate_publication_layout_binding",
    "publication_layout_parameters",
    "publication_layout_report",
    "new_publication_figure_style_profile",
    "validate_publication_figure_style_profile",
    "publication_figure_style_profile",
    "bind_publication_figure_style",
    "validate_publication_figure_style_binding",
    "publication_figure_parameters",
    "publication_figure_accessibility_audit",
    "new_publication_submission_package_spec",
    "validate_publication_submission_package_spec",
    "new_publication_supplementary_index",
    "validate_publication_supplementary_index",
    "new_publication_submission_package_manifest",
    "validate_publication_submission_package_manifest",
    "publication_submission_package_report",
    "new_publication_ordination_spec",
    "validate_publication_ordination_spec",
    "new_publication_ordination_output",
    "validate_publication_ordination_output",
    "publication_ordination_caption",
    "publication_ordination_report",
    "new_publication_dapc_spec",
    "validate_publication_dapc_spec",
    "new_publication_dapc_output",
    "validate_publication_dapc_output",
    "publication_dapc_caption",
    "publication_dapc_report",
    "canonical_1000g_chrY_source",
    "validate_canonical_source",
    "verify_canonical_source",
    "canonical_dataset_from_source",
    "approved_1000g_chrY_registry",
    "write_approved_canonical_source_evidence"
  ))
}
